### PR TITLE
fix ''should not push route with duplicated key" issue

### PR DESCRIPTION
**Pull request by kyaroru**

### CODE REVIEW

**Comment by callmephilip** [comment]
i think this makes sense. do you mind adding tests for this as well? you can run `gulp watch` and add a test for card stack reducer: https://github.com/bakery/react-native-navigation-redux-helpers/blob/master/test/unit/reducers.js#L94

**Comment by kyaroru** [comment]
i have added the test, but I not sure whether it is the correct way to write test spec >_<

**Comment by callmephilip** [comment]
released in 0.5.0. thank you for your contribution 🙌

**Comment by kyaroru** [comment]
thanks for merging !! it's my first time sending pull request in git >_<

**Pull request merged**
